// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/nfa/cath.gold"
package nfa;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import nfa.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class cath {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix(GCollections.asSet("A","B","C","D","E","F","G","H","I"));
      $line=6;
      Object \u03A3=$fix(GCollections.asSet('c','a','t','h'));
      $line=7;
      Object q_0=$fix("A");
      $line=8;
      Object F=$fix(GCollections.asSet("E","F","G","H"));
      $line=9;
      Object \u0394=$fix(new Object[]{new Object[]{"A",'\u03BB',"B"},new Object[]{"B",'c',"B"},new Object[]{"B",'a',"B"},new Object[]{"B",'t',"B"},new Object[]{"B",'h',"B"},new Object[]{"B",'h',"C"},new Object[]{"C",'a',"D"},new Object[]{"D",'t',"E"},new Object[]{"E",'c',"E"},new Object[]{"E",'a',"E"},new Object[]{"E",'t',"E"},new Object[]{"E",'h',"E"},new Object[]{"A",'\u03BB',"F"},new Object[]{"F",'a',"F"},new Object[]{"F",'t',"F"},new Object[]{"F",'h',"F"},new Object[]{"F",'c',"G"},new Object[]{"G",'t',"F"},new Object[]{"G",'h',"F"},new Object[]{"G",'c',"G"},new Object[]{"G",'a',"H"},new Object[]{"H",'a',"F"},new Object[]{"H",'h',"F"},new Object[]{"H",'c',"G"},new Object[]{"H",'t',"I"},new Object[]{"I",'c',"I"},new Object[]{"I",'a',"I"},new Object[]{"I",'t',"I"},new Object[]{"I",'h',"I"}});
      $line=19;
      Object A=$fix($invokeConstructor(GNondeterministicAutomaton.class,new Object[]{Q,\u03A3,q_0,F,\u0394}));
      $line=20;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,cath.class,"main",$line);
    }
  }
}
