// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/nfa/example.gold"
package nfa;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import nfa.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class example {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix(GCollections.asSet("A","B"));
      $line=6;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=7;
      Object qI=$fix("A");
      $line=8;
      Object F=$fix(GCollections.asSet("B"));
      $line=9;
      Object \u0394=$fix(new Object[]{new Object[]{"A",'1',"B"},new Object[]{"B",'1',"A"},new Object[]{"A",'0',"A"},new Object[]{"B",'0',"B"}});
      $line=13;
      Object A=$fix($invokeConstructor(GNondeterministicAutomaton.class,new Object[]{Q,\u03A3,qI,F,\u0394}));
      $line=14;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,example.class,"main",$line);
    }
  }
}
