// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/pda/grammar.gold"
package pda;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import pda.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class grammar {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix(GCollections.asSet("A","B","C"));
      $line=6;
      Object \u03A3=$fix(GCollections.asSet('a','b'));
      $line=7;
      Object \u0393=$fix(GCollections.asSet('S','a','b','$'));
      $line=8;
      Object qI=$fix("A");
      $line=9;
      Object F=$fix(GCollections.asSet("C"));
      $line=10;
      Object A=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,qI,F}));
      $line=11;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)A).delta("A","B",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=12;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)A).delta("B","B",$cast(java.lang.String.class,"a")),new Object[]{"a"});
      $line=13;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)A).delta("B","B",$cast(java.lang.String.class,"b")),new Object[]{"b"});
      $line=14;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)A).delta("B","B",$cast(java.lang.String.class,"")),new Object[]{"S","ba"});
      $line=15;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)A).delta("B","B",$cast(java.lang.String.class,"")),new Object[]{"$","bSa"});
      $line=16;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)A).delta("B","B",$cast(java.lang.String.class,"")),new Object[]{"S","bSa"});
      $line=17;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)A).delta("B","C",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=21;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,grammar.class,"main",$line);
    }
  }
}
