// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/pda/WFF.gold"
package pda;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import pda.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class WFF {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix(GCollections.asSet("A","B","C","D"));
      $line=6;
      Object \u03A3=$fix($opUnionY($opIntvlY('p','s'),GCollections.asSet('(',')','A','O','N','I')));
      $line=7;
      Object \u0393=$fix(GCollections.asSet('P'));
      $line=8;
      Object qI=$fix("A");
      $line=9;
      Object F=$fix(GCollections.asSet("A","C","D"));
      $line=10;
      Object A=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,qI,F}));
      $line=11;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)A).delta("A","B",$cast(java.lang.String.class,"(")),new Object[]{"P"});
      $line=12;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)A).delta("B","B",$cast(java.lang.String.class,"(")),new Object[]{"P"});
      $line=13;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)A).delta("A","C",$cast(java.lang.String.class,"p")),new Object[]{});
      $line=14;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)A).delta("C","D",$cast(java.lang.String.class,'A')),new Object[]{});
      $line=15;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)A).delta("A","D",$cast(java.lang.String.class,'A')),new Object[]{});
      $line=16;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)A).delta("B","C",$cast(java.lang.String.class,"p")),new Object[]{});
      $line=17;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)A).delta("C","A",$cast(java.lang.String.class,")")),new Object[]{"P"});
      $line=18;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)A).delta("D","A",$cast(java.lang.String.class,"")),new Object[]{});
      $line=19;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)A).delta("D","A",$cast(java.lang.String.class,")")),new Object[]{"P"});
      $line=20;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)A).delta("A","A",$cast(java.lang.String.class,")")),new Object[]{"P"});
      $line=23;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,WFF.class,"main",$line);
    }
  }
}
