// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/dfa/regex/Eight.gold"
package dfa.regex;
import dfa.regex.*;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Eight {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix($opIntvlY(0,3));
      $line=6;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=7;
      Object qI=$fix(0);
      $line=8;
      Object F=$fix(GCollections.asSet(3));
      $line=9;
      Object A=$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,qI,F,new GMethod(Eight.class,"\u03B4")}));
      $line=10;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Eight.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=14;
      if ($opEqualY(q,0)) {
        $line=15;
        $result=1;
        if (true) break $try;
      }
      else {
        $line=16;
        if ($opEqualY(q,1)) {
          $line=17;
          $result=2;
          if (true) break $try;
        }
        else {
          $line=19;
          $result=3;
          if (true) break $try;
        }
      }
      $line=21;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Eight.class,"\u03B4",$line);
    }
    return $result;
  }
}
