// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/dfa/regex/Nine.gold"
package dfa.regex;
import dfa.regex.*;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Nine {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix($opIntvlY(0,3));
      $line=6;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=7;
      Object qI=$fix(0);
      $line=8;
      Object F=$fix(GCollections.asSet(1,2,3));
      $line=9;
      Object \u0394=$fix(new Object[]{new Object[]{0,'1',0},new Object[]{0,'0',0},new Object[]{0,'0',1},new Object[]{0,'1',2},new Object[]{2,'0',3},new Object[]{2,'1',3}});
      $line=15;
      Object A=$fix($invokeConstructor(GNondeterministicAutomaton.class,new Object[]{Q,\u03A3,qI,F,\u0394}));
      $line=16;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Nine.class,"main",$line);
    }
  }
}
