// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/dfa/regex/Two.gold"
package dfa.regex;
import dfa.regex.*;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Two {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=6;
      Object Q=$fix($opIntvlY(0,1));
      $line=7;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=8;
      Object qI=$fix(0);
      $line=9;
      Object F=$fix(GCollections.asSet(0));
      $line=10;
      Object A=$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,qI,F,new GMethod(Two.class,"\u03B4")}));
      $line=11;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Two.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=15;
      if ($opEqualY(\u03C3,'0')) {
        $line=16;
        $result=$opModulY($opAdditY(q,1),2);
        if (true) break $try;
      }
      else {
        $line=18;
        $result=q;
        if (true) break $try;
      }
      $line=20;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Two.class,"\u03B4",$line);
    }
    return $result;
  }
}
