// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/structures/structures.gold"
package structures;
import gold.util.*;
import java.lang.*;
import org.apfloat.*;
import structures.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class structures {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=3;
      Object Set1=$fix($opIntvlY(1,10));
      $line=4;
      Object Set2=$fix(GCollections.asSet(1,2,3,5,6,7));
      $line=5;
      Object Set=$fix(GCollections.emptySet());
      $line=6;
      Object elem=$fix(4);
      $line=9;
      if ($opMembrY(elem,Set1)) {
        $line=10;
        Set=$fix($opDiffeY(Set1,GCollections.asSet(elem)));
      }
      else {
        $line=11;
        if ($opMembrY(elem,Set2)) {
          $line=12;
          Set=$fix($opUnionY(Set,GCollections.asSet(elem)));
        }
        else {
          $line=14;
          Set2=$fix($opUnionY(Set,GCollections.asSet(elem)));
        }
      }
      $line=18;
      for (int i=$int(1); i<=$int(10); i++) {
        $line=19;
        System.out.println($message(new Object[]{$opAdditY(" Counter : ",i)}));
      }
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,structures.class,"main",$line);
    }
  }
  public static Integer greater(Object a, Object b) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=28;
      if ($opGreatY(a,b)) {
        $line=29;
        $result=a;
        if (true) break $try;
      }
      else {
        $line=31;
        $result=b;
        if (true) break $try;
      }
      $line=33;
      $rethrow(new RuntimeException("The function \"greater(a:Object,b:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,structures.class,"greater",$line);
    }
    return $cast(Integer.class,$result);
  }
  public static Object sumOne(Integer param) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=38;
      Object res=$fix($opAdditY(param,1));
      $line=39;
      System.out.println($message(new Object[]{res}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,structures.class,"sumOne",$line);
    }
    return $result;
  }
}
