// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/dfa/crossp.gold"
package dfa;
import dfa.*;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class crossp {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q1=$fix(GCollections.asSet('A','B'));
      $line=6;
      Object Q2=$fix($opIntvlY('a','b'));
      $line=7;
      gold.structures.set.ISet $v1=$newSet();
      $v2:for (Object p:GCollections.unmodifiableCollection(Q1)) {
        for (Object q:GCollections.unmodifiableCollection(Q2)) {
          $v1.add(GCollections.asList(p,q));
        }
      }
      Object Q=$fix($v1);
      $line=8;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=9;
      Object qI=$fix(GCollections.asList('A','a'));
      $line=10;
      Object F1=$fix(GCollections.asSet('B'));
      $line=11;
      Object F2=$fix(GCollections.asSet('a'));
      $line=12;
      gold.structures.set.ISet $v3=$newSet();
      $v4:for (Object p:GCollections.unmodifiableCollection(F1)) {
        for (Object q:GCollections.unmodifiableCollection(F2)) {
          $v3.add(GCollections.asList(p,q));
        }
      }
      Object F=$fix($v3);
      $line=13;
      Object A=$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,qI,F,new GMethod(crossp.class,"\u03B4")}));
      $line=14;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,crossp.class,"main",$line);
    }
  }
  public static Object \u03B4(java.lang.Iterable $v5, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v6=GCollections.unmodifiableCollection($v5).iterator();
      Object p=$v6.next();
      Object q=$v6.next();
      $line=18;
      Object newp=$fix(Character.toChars($int($opAdditY($opModulY($opAdditY($opSubtrY(p,'A'),1),2),'A'))));
      $line=19;
      if ($opEqualY(\u03C3,'1')) {
        $line=20;
        Object newq=$fix(Character.toChars($int($opAdditY($opModulY($opAdditY($opSubtrY(1,'a'),1),2),'a'))));
        $line=21;
        $result=GCollections.asList($getArrayValue(newp,new Object[]{0}),$getArrayValue(newq,new Object[]{0}));
        if (true) break $try;
      }
      else {
        $line=23;
        $result=GCollections.asList($getArrayValue(newp,new Object[]{0}),q);
        if (true) break $try;
      }
      $line=25;
      $rethrow(new RuntimeException("The function \"\u03B4(\u27E8p,q\u27E9:java.lang.Iterable,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,crossp.class,"\u03B4",$line);
    }
    return $result;
  }
}
