// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/dfa/date.gold"
package dfa;
import dfa.*;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class date {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix($opIntvlY(0,15));
      $line=6;
      Object \u03A3=$fix($opUnionY($opIntvlY('0','9'),GCollections.asSet('/','-','.')));
      $line=7;
      Object qI=$fix(0);
      $line=8;
      Object F=$fix(GCollections.asSet(14));
      $line=9;
      Object \u0394=$fix(new Object[]{new Object[]{0,'0',1},new Object[]{0,'1',2},new Object[]{1,'0',3},new Object[]{1,'1',3},new Object[]{1,'2',3},new Object[]{1,'3',3},new Object[]{1,'4',3},new Object[]{1,'5',3},new Object[]{1,'6',3},new Object[]{1,'7',3},new Object[]{1,'8',3},new Object[]{1,'9',3},new Object[]{2,'0',4},new Object[]{2,'1',4},new Object[]{2,'2',4},new Object[]{3,'/',5},new Object[]{4,'/',5},new Object[]{5,'0',6},new Object[]{5,'1',6},new Object[]{5,'2',6},new Object[]{5,'3',8},new Object[]{8,'0',9},new Object[]{8,'1',9},new Object[]{6,'0',7},new Object[]{6,'1',7},new Object[]{6,'2',7},new Object[]{6,'3',7},new Object[]{6,'4',7},new Object[]{6,'5',7},new Object[]{6,'6',7},new Object[]{6,'7',7},new Object[]{6,'8',7},new Object[]{6,'9',7},new Object[]{9,'/',10},new Object[]{7,'/',10},new Object[]{10,'0',11},new Object[]{10,'1',11},new Object[]{10,'2',11},new Object[]{11,'0',12},new Object[]{11,'1',12},new Object[]{11,'2',12},new Object[]{11,'3',12},new Object[]{11,'4',12},new Object[]{11,'5',12},new Object[]{11,'6',12},new Object[]{11,'7',12},new Object[]{11,'8',12},new Object[]{11,'9',12},new Object[]{12,'0',13},new Object[]{12,'1',13},new Object[]{12,'2',13},new Object[]{12,'3',13},new Object[]{12,'4',13},new Object[]{12,'5',13},new Object[]{12,'6',13},new Object[]{12,'7',13},new Object[]{12,'8',13},new Object[]{12,'9',13},new Object[]{13,'0',14},new Object[]{13,'1',14},new Object[]{13,'2',14},new Object[]{13,'3',14},new Object[]{13,'4',14},new Object[]{13,'5',14},new Object[]{13,'6',14},new Object[]{13,'7',14},new Object[]{13,'8',14},new Object[]{13,'9',14}});
      $line=23;
      Object A=$fix($invokeConstructor(GNondeterministicAutomaton.class,new Object[]{Q,\u03A3,qI,F,\u0394}));
      $line=24;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,date.class,"main",$line);
    }
  }
}
