// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/automata/dfa.gold"
package automata;
import automata.*;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class dfa {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=6;
      Object Q=$fix(GCollections.asSet("Just1","Read0","Read01"));
      $line=7;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=8;
      Object q=$fix("Just1");
      $line=9;
      Object F=$fix(GCollections.asSet("Read01"));
      $line=10;
      Object A=$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,new GMethod(dfa.class,"\u03B4")}));
      $line=11;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,dfa.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=15;
      if (($opEqualY(q,"Just1")&&$opEqualY(\u03C3,'0'))) {
        $line=16;
        $result="Read0";
        if (true) break $try;
      }
      else {
        $line=17;
        if (($opEqualY(q,"Read0")&&$opEqualY(\u03C3,'1'))) {
          $line=18;
          $result="Read01";
          if (true) break $try;
        }
        else {
          $line=20;
          $result=q;
          if (true) break $try;
        }
      }
      $line=22;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,dfa.class,"\u03B4",$line);
    }
    return $result;
  }
}
